modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="terrraria"
version="1.0.0"
displayName="Terrraria"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Martin, MCreator"

[[dependencies.terrraria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




